---
parameters:
  deployer_username: vagrant
  php:
    maxfilesize: '20M'
  memcached:
    ip: 127.0.0.1
    port: 11211
  apache:
    port: 81
  applications:
    - name:       project_name
      template:   symfony2-dev-application
      domain:     www.project_name.loc
      path:       /var/www/sites/www.project_name.loc
    - name:       test_project_name
      template:   symfony2-test-application
      domain:     test.project_name.loc
      path:       /var/www/sites/www.project_name.loc
  mysql:
    ip: 127.0.0.1
    root_password: n0p455
  databases:
    - name: project_name_dev
    - name: project_name_test
  database_users:
    - username: project_name
      password: n0p455
      db_name: project_name_%
  git:
    rate_limit_token:   ADD-YOUR-OWN
  selenium:
    path:       /usr/lib/selenium
    log_path:   /var/log/selenium
    url:        http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar
    filename:   selenium-server-standalone-2.53.0.jar
  timezone: 'UTC'
